:title-page: 
:icons:
:imagesdir: img
:toc: macro
:toc-title: Contents
:toclevels: 2
:figure-caption!:

:extension: jpg

[[klara-laznickova]]
= Klára Lázničková: Portfolio

== Curriculum vitae

=== Education

* 2019-now: Master's study at Faculty of Fine Arts, BUT, Studio Environment, Barbora Klímová
* 2018-now: Master's study at Faculty of Fine Arts, OSU, Studio of Painting 1, Daniel Balabán
* 2015-2018: Bachelor's study at Faculty of Fine Arts, OSU, Studio of Painting 1, Daniel Balabán
** SS 2016/2017 internship at Faculty of Fine Arts, BUT, Studio Environment, Barbora Klímová
** WS 2016/2017 internship at Faculty of Fine Arts, BUT, Studio of Painting 2, Luděk Rathouský
* 2011-2015: Secondary School of Applied Arts and Higher School of Applied Arts, Prague

=== Exhibitions

* 2019
** Party-Extinct-Repeat, 3-day long performance with Global Genocide Collective, Terén - CED, Brno
** Pilgrimage to Stará Boleslav - st. Anthony (collective)
* 2018
** exhibition of bachelor thesis Tygo Dream 
(Pneuservis, VEGA healthy food, Ostrava City Library branch office Daliborova, Maryčka - cafe, Žalák - pub, Plato - wc in gallery, Salvation Army, Boček - bakery, FER@NET net -  cafe, Salt cave Halos)
* 2018
** Comfort balcony, Michal Mine, Ostrava (collective)
* 2017
** Studio Environment - To All, Cyril gallery, Prostìjov (collective)
* 2015
** Mystery puzzle, Teplárna cafe, Brno
** Pilgrimage to Stará Boleslav  (collective)
* 2014
** Pilgrimage to Stará Boleslav  (collective)

=== Contact

- https://laznickova-klara.tumblr.com
- laznickova.kl@gmail.com


<<<
== Portfolio

[[diykobraz]]
=== DIYkobraz

This project is a zin called DIYkobraz.
Its contents are old anecdotas and my drawings with which I connect them.
The old jokes I collected primarily from czechoslovakian humorous and satirical magazine called Dikobraz (porcupine) which was focus on cartoon jokes and anecdotes of many themes - mainly covertly political.
I collected anecdote based on ecologic and rather more civilization theme.
These anecdotes are mostly from 60s to 80s.

In this project I want to show to my generation the ecological language that comes from generations of our parents and grandparents and also try to update or disrupt these old jokes a little with my drawings.


.DIYkobraz, detail of page, digital print, 2020.
image::15-diykobraz/pf.{extension}[,450]
.DIYkobraz, detail of page, digital print, 2020.
image::15-diykobraz/autak.{extension}[,450]

<<<
[[visual-poem]]
=== Visual Poem

This semestral work is made in the form of wallpaper. It's called Visual Poem. It deals with possibilities of communication - transmission of information or impression through visual way.

I applied pictorial text on a column with A4 format papers. It was supposed to evoke advertising wallpapering roller.
Repeating and in-line arrangement of the wallpaper looks for me similar to a (lyrical) poem.
Its content is perceived primarily intuitively - in the form of association through the image component.

Negative stimulus on the mind (related for example with climatic crisis or the rush of time...) makes me feel stressed, sad and anxious.
But my mind wants to resist of negative stimulus.
It create a defensive system in the form of positive images - they glitch itself.
My mind tries to escape to the safe zone.
This safe zone is found in nostalgia and childhood, especially in pure children's interests and ideals – like admiration of spring flowers or esteem for trees.
The poem illustrates my clogged mind reflecting in it self the pressure of society and the state of the world.
The topic is generally the principle of how children look at the world - with pure love and passion, which I want to remind in some way to adult lethargic world.

.Design sketch, digital print, A3, 2019.
image::14-vizualni-basen/skica.{extension}[,650]
.Visual poem - instalation, glued digital print A4, 2019.
image::14-vizualni-basen/sloup2.{extension}[,650]


<<<
[[pilgrimage]]
=== Pilgrimage of Saint Anthony

15th Pilgrimage to Stará Boleslav on topic of the Temptation of St. Anthony - Jesus' Fish and Miracle in Rimini

.St. Anthony's Aquarium, watercolor on paper, 2019.
image::13-kaplicky-sv-antonin/20190427_185351.{extension}[,650]


<<<
[[instant-coziness]]
=== Instant coziness

Finding and defining "instant coziness" which creates my internal and external environment.

.Slippers, oil on canvas, 2019.
image::12-klauzury/papuce.{extension}[,500]
.Aquarium, oil on canvas, 2019.
image::12-klauzury/akvarium.{extension}[,500]
.Čuník’s Bowl, oil on canvas, 2019.
image::12-klauzury/miskaprocunika.{extension}[,500]
.Palm, oil on canvas, 2019.
image::12-klauzury/palma.{extension}[,500]
.Things, oil on canvas, 2019.
image::12-klauzury/veci.{extension}[,]


<<<
[[floatacni-tygri]]
=== Floatation Tigers

Dear baby Jesus, I wish under the tree a mobile phone with a snake, crayons mainly pink, inflatable castle, bike and tiger or the elephant, who can fly through the ears.
And the tiger must be calm, in order they not want to eat our dog Žeryk,
thanks Klárka Lázničková.                                                                

I want tiger as a pet. Isn't it a escaping from hurried and precarized
adult world to calm and sweet childhood? This cycle of painting is inspired
by criminal case connected to tiger masox and breeding of exotic felines by private individuals in the Czech Republic.+

The installation works with the topic of perception of painting.
Its main conception tries to support relaxing feeling of the exhibition space and lures the visitor to spend longer time in the space,
which allows deeper concentration onto the visuality of paintings.

The painting is not an index of the painted motive, but instead it carries relaxing feelings.
The observer might let her mind float in the flow of visual thinking in the similar way as the objects on the paintings are floating.

.Floatation Tigers, oil on canvas , 2018.
image::11-floatacni-tygri/floa0.{extension}[,650]
.Installation - Comfort balcony, 2019.
image::11-floatacni-tygri/floa1.{extension}[,650]
.Installation - Comfort balcony, 2019.
image::11-floatacni-tygri/floa3.{extension}[,650]
.Installation - Comfort balcony, 2019.
image::11-floatacni-tygri/floa2.{extension}[,650]


<<<
=== Tygo dream

My bachelor thesis called Tygo Dream is focus of sensitive and suggestiv properties of painting.
In many cases, I identified myself with thought and theories of modern painters for example : The image is a chaise lounge for the soul.
I created cyklus of painting (Tiger, Palm, Fable) deals with this topic. The whole work was made in a slightly exaggerated tone. One of the aims was to prevent the fear that was evident in the post-election Ostrava. I used the classic method of oil painting and installed created paintings  in semi-public spaces in Ostrava. Without much ambition, I let them perform their common (contemplative, meditative, aesthetic and decorativ)  function.
I had need to stress simple and basal, but I think essential properties of painting.


.Tygodream, installation - FER@NET net Cafe, 2018.
image::10-tygodream/bajka010.{extension}[]
.Tygodream, installation - Boček Bakery, 2018.
image::10-tygodream/klara004.{extension}[]
.Tygodream, installation - tire service, 2018.
image::10-tygodream/klara005.{extension}[]
.Tygodream, installation - VEGA healthy nutrition shop, 2018.
image::10-tygodream/klara016.{extension}[]
.Tygodream, installation - Maryčka Cafe, 2018.
image::10-tygodream/klara020.{extension}[]
.Tygodream, installation - Plato Gallery, 2018.
image::10-tygodream/klara019.{extension}[]
.Tygodream, installation - Salvation Army, 2018.
image::10-tygodream/bajka011.{extension}[]


<<<
[[tygo-dream-bajka]]
==== Bajka

.Lion and mole, oil on canvas, 2018.
image::9-tygodream-bajka/lev-a-krtek.{extension}[,600]
.Fable, oil on canvas, 2018.
image::9-tygodream-bajka/bajka.{extension}[,600]
.Mole, oil on canvas, 2018.
image::9-tygodream-bajka/krtek.{extension}[,650]
.Lion, oil on canvas, 2018.
image::9-tygodream-bajka/predlozka.{extension}[,550]
.Lion, oil on canvas, 2018.
image::9-tygodream-bajka/bajka001.{extension}[,550]
.Lion, oil on canvas, 2018.
image::9-tygodream-bajka/lev1.{extension}[,650]
.Lion, oil on canvas, 2018.
image::9-tygodream-bajka/lev2.{extension}[,500]
.Cosmic Lion, oil on canvas, 2018.
image::9-tygodream-bajka/vesmirnylev.{extension}[,500]
.Crocodile, oil on canvas, 2018.
image::9-tygodream-bajka/bajka008.{extension}[,500]
.Kitten, oil on canvas, 2018.
image::9-tygodream-bajka/bajka009.{extension}[,500]


<<<
[[tygo-dream-palma-more-slunce]]
==== Holiday: Palm, Sea, Sun

.Plato, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/platorovne002.{extension}[]
.Orion, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/orion.{extension}[,570]
.Strawberry, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/jahodova.{extension}[,570]
.Margot, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/margot.{extension}[,570]
.New Beetle, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/new-beetle.{extension}[,570]
.Lion, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/lev.{extension}[,500]
.Husk, oil on canvas, 2018.
image::8-tygodream-palma-more-slunce/lusk.{extension}[,500]


<<<
[[zvrchu-tygo-dream]]
==== From the Top

situation/still life painted from the top, things which losing their matter. Content of things are emptied and everything becomes just an abstract composition.


.Rug, oil on canvas, 2018.
image::7-tygodream-zvrchu/tygr003.{extension}[]
.Tiger, oil on canvas, 2017.
image::7-tygodream-zvrchu/tygr.{extension}[]
.Horse, oil on canvas, 2017.
image::7-tygodream-zvrchu/kone.{extension}[,400]
.Still life, oil on canvas, 2017.
image::7-tygodream-zvrchu/zatisi.{extension}[,400]
.Tygo dream, oil on canvas, 2017.
image::7-tygodream-zvrchu/tygo-dream.{extension}[,470]
.Armchair, oil on canvas, 2017.
image::7-tygodream-zvrchu/kreslo.{extension}[,470]


<<<
[[tygri-tygo-dream]]
==== Tigers

Tiger as a pop-cultural lightmotive and easily understandable symbol for viewer, because of its frequent use in advertisiment.
 

.Tiger, oil on canvas, 2018.
image::6-tygodream-tygri/tygr1.{extension}[,470]
.Tiger, oil on canvas, 2018.
image::6-tygodream-tygri/tygr3.{extension}[,470]
.Tiger, oil on canvas, 2018.
image::6-tygodream-tygri/tygo25.{extension}[,400]
.Tiger, oil on canvas, 2018.
image::6-tygodream-tygri/tygr2t.{extension}[,400]
.Tiger, oil on canvas, 2018.
image::6-tygodream-tygri/tygr4.{extension}[,400]
.Tygonanas, oil on canvas, 2018.
image::6-tygodream-tygri/tygonanas.{extension}[,400]


<<<
[[archivacni-basen]]
=== Archival Poem

This semestral work deals with archive of family records in electronic form.
My Archival poem include collected materials like forgotten videos which content are three years of growing and progress of my little sister in her newborn life.
I find this videos in our electronic mess -  in our cards and disks.
All of these videos have topic of my sister and their progress and all are recorded in our living room.
This is equivalent to the fact  that each such videos include sounds of TV in their background.
In my poem I rewrite contains of this videos.
In right side you can see column where it is written what my sister did.
With distance of years it look like that she does nothing.
For example she try to caress a dog or eat croissant or brush her teeth.
In the left side is exact transcribe of TV sounds.
Specifically I rewrited heared parts of the interview comes from TV shows like crime detective stories, documents about nature etc. 
In the end of this poem are citation which contains names of programs, tv station and time and year of playing.

Poem keeps, shown us and reveals little bit sensitive and unwanted information about our free time with mass media much more than about newborn life.


.Archival Poem, print, 2017.
image::5-archivacni-basen/letak.{extension}[,500]
image::5-archivacni-basen/arb.{extension}[,500]
image::5-archivacni-basen/arb2.{extension}[,500]


<<<
[[obraz-a-kocka]]
=== The Painting and the Cat

In this project I made scrubbers for the cat. The project started so that I am want to paint without much more unnecessary details.
I used for painting instead canvas alternative materials like old blankets and towels.
Materials that have a high structure which does not allow painted in detail.
These my painting - blankets stretched on blind frame - was used by my cats as scrubber.
So then I got idea to make ideal scrubber for our environment.
Because I hate classic cat equipment that is ugly and divides the flat into cats environment and myspace.
So I made special scrubber in the form of a armchair which was made of these attractive materials for cats as paintings - blankets and blind frame and I visually infiltrate them into myspace.

.Painting and Cat, text, 2016.
image::4-obraz-a-kocka/text.{extension}[,650]
.Painting and Cat: installation, view into installation, 2016.
image::4-obraz-a-kocka/instalace.{extension}[,500]
.Painting and Cat: infiltration, view into installation, 2016.
image::4-obraz-a-kocka/infiltrace1.{extension}[,500]
.Painting and Cat: infiltration, view into installation, 2016.
image::4-obraz-a-kocka/infiltrace2.{extension}[,500]
.Painting and Cat: scratcher, view into installation, 2016.
image::4-obraz-a-kocka/skrabadla.{extension}[]


<<<
[[animals]]
=== Animals

I try to empty the motive and only percieve the subject in abstract dimensions.
I focus on physical constitution of animals in different situation, positions or phases of movement but I take its mass just as an abstract shape. 
This shape is further simplified and cleaned from unimportant visual noises.
I also used the natural compositions of animals in their raw form - just how they happened during the day or night.

Frames are coated with alternative materials like towels or blankets which structure might resemble animal fur.
Also its structure makes it harder to paint in detail, which pushes me as a painter into the need for much more simplified shapes.

.Cats, oil on canvas, 2016.
image::3-zvirata/kocky7.{extension}[,600]
.Cats, oil on canvas, 2016.
image::3-zvirata/kocky4.{extension}[,500]
.Cats, oil on canvas, 2016.
image::3-zvirata/kocky5.{extension}[,500]
.Cats, oil on canvas, 2016.
image::3-zvirata/kocky8.{extension}[,600]
.Cats, oil on canvas, 2016.
image::3-zvirata/kocky9.{extension}[,600]
.Chickens, oil on canvas, 2016.
image::3-zvirata/kurata.{extension}[,600]
.Dog, oil on canvas, 2016.
image::3-zvirata/pes.{extension}[,600]
.Hen, oil on canvas, 2016.
image::3-zvirata/slepice.{extension}[,600]

<<<
[[rodina]]
=== Family

This work is about searching for inspiring moments or compositions in my everyday life.
The paintings are cleansed from unwanted aspects of reality - of visual noise of ugly things.
This choice of what should be cleansed is based just on my visual preferences.

.Deathfolk, 120x120cm, oil on canvas, 2016.
image::2-rodina/deathfolk.{extension}[]
.Small Rucksack, 105x140cm, oil on canvas, 2016.
image::2-rodina/batuzek.{extension}[,600]
.Eskimos, 110x110cm, oil on canvas, 2016.
image::2-rodina/eskimaci.{extension}[,600]
.Anežka, 80x80cm, oil on canvas, 2016.
image::2-rodina/anezka.{extension}[,450]
.Bella, 80x80cm, oil on canvas, 2016.
image::2-rodina/bella.{extension}[,450]


<<<
[[biotope]]
=== Biotope

This work explores the bonds between things and their owner and also meaning of constelation of things in the space.
Is it just random or does it have any deeper meaning? What does it tell about the owner?
In this work I try to understand the things as animals or plants.
Using this concept I explore the specificity of the fauna and flora and then through
reorganization of paintings in the space I create new specific bio envritonment - a biotope.

.Biotop, dimensions variable, installation, 2016.
image::1-biotop/biotop-instalace.{extension}[]
.Mandrill, 35x40cm, oil on canvas, 2016.
image::1-biotop/mandril.{extension}[,600]
.Cabin, 65x75cm, oil on canvas, 2016.
image::1-biotop/chata1.{extension}[,500]
.Cats, 130x120cm, oil on canvas, 2016.
image::1-biotop/kocky.{extension}[,500]
.Shelf, 80x100cm, oil on canvas, 2016.
image::1-biotop/policka1.{extension}[,500]
.Úprka, 70x70cm, oil on canvas, 2016.
image::1-biotop/uprka.{extension}[,500]
